/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PackedUserOperationStruct = {
  sender: AddressLike;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  accountGasLimits: BytesLike;
  preVerificationGas: BigNumberish;
  gasFees: BytesLike;
  paymasterAndData: BytesLike;
  signature: BytesLike;
};

export type PackedUserOperationStructOutput = [
  sender: string,
  nonce: bigint,
  initCode: string,
  callData: string,
  accountGasLimits: string,
  preVerificationGas: bigint,
  gasFees: string,
  paymasterAndData: string,
  signature: string
] & {
  sender: string;
  nonce: bigint;
  initCode: string;
  callData: string;
  accountGasLimits: string;
  preVerificationGas: bigint;
  gasFees: string;
  paymasterAndData: string;
  signature: string;
};

export interface AgentGatePaymasterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStake"
      | "deposit"
      | "depositForEndpoint"
      | "depositForEndpointHash"
      | "endpointBalance"
      | "endpointGasShareBps"
      | "endpointGasShareIsSet"
      | "endpointOwner"
      | "entryPoint"
      | "fundAndSetGasShare"
      | "getDeposit"
      | "getTotalSponsored"
      | "owner"
      | "postOp"
      | "renounceOwnership"
      | "setGasShare"
      | "setGasShareByHash"
      | "totalCalls"
      | "totalSponsored"
      | "transferOwnership"
      | "unlockStake"
      | "validatePaymasterUserOp"
      | "withdrawEndpointBalance"
      | "withdrawFunds"
      | "withdrawStake"
      | "withdrawTo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EndpointFunded"
      | "EndpointGasShareSet"
      | "EndpointWithdraw"
      | "GasSponsored"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositForEndpoint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForEndpointHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointGasShareBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointGasShareIsSet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundAndSetGasShare",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSponsored",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postOp",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGasShare",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasShareByHash",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCalls",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSponsored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validatePaymasterUserOp",
    values: [PackedUserOperationStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEndpointBalance",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTo",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositForEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForEndpointHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointGasShareBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointGasShareIsSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundAndSetGasShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postOp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasShareByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalCalls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePaymasterUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEndpointBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdrawTo", data: BytesLike): Result;
}

export namespace EndpointFundedEvent {
  export type InputTuple = [
    endpointHash: BytesLike,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    endpointHash: string,
    funder: string,
    amount: bigint
  ];
  export interface OutputObject {
    endpointHash: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndpointGasShareSetEvent {
  export type InputTuple = [endpointHash: BytesLike, bps: BigNumberish];
  export type OutputTuple = [endpointHash: string, bps: bigint];
  export interface OutputObject {
    endpointHash: string;
    bps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndpointWithdrawEvent {
  export type InputTuple = [
    endpointHash: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [endpointHash: string, to: string, amount: bigint];
  export interface OutputObject {
    endpointHash: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasSponsoredEvent {
  export type InputTuple = [
    agent: AddressLike,
    endpointHash: BytesLike,
    gasUsed: BigNumberish,
    gasShareBps: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    endpointHash: string,
    gasUsed: bigint,
    gasShareBps: bigint
  ];
  export interface OutputObject {
    agent: string;
    endpointHash: string;
    gasUsed: bigint;
    gasShareBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentGatePaymaster extends BaseContract {
  connect(runner?: ContractRunner | null): AgentGatePaymaster;
  waitForDeployment(): Promise<this>;

  interface: AgentGatePaymasterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStake: TypedContractMethod<
    [unstakeDelaySec: BigNumberish],
    [void],
    "payable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositForEndpoint: TypedContractMethod<[url: string], [void], "payable">;

  depositForEndpointHash: TypedContractMethod<
    [endpointHash: BytesLike],
    [void],
    "payable"
  >;

  endpointBalance: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  endpointGasShareBps: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  endpointGasShareIsSet: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  endpointOwner: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  fundAndSetGasShare: TypedContractMethod<
    [url: string, bps: BigNumberish],
    [void],
    "payable"
  >;

  getDeposit: TypedContractMethod<[], [bigint], "view">;

  getTotalSponsored: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postOp: TypedContractMethod<
    [
      mode: BigNumberish,
      context: BytesLike,
      actualGasCost: BigNumberish,
      actualUserOpFeePerGas: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGasShare: TypedContractMethod<
    [url: string, bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasShareByHash: TypedContractMethod<
    [endpointHash: BytesLike, bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalCalls: TypedContractMethod<[], [bigint], "view">;

  totalSponsored: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockStake: TypedContractMethod<[], [void], "nonpayable">;

  validatePaymasterUserOp: TypedContractMethod<
    [
      userOp: PackedUserOperationStruct,
      userOpHash: BytesLike,
      maxCost: BigNumberish
    ],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;

  withdrawEndpointBalance: TypedContractMethod<
    [url: string, to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawStake: TypedContractMethod<
    [withdrawAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawTo: TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<[unstakeDelaySec: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositForEndpoint"
  ): TypedContractMethod<[url: string], [void], "payable">;
  getFunction(
    nameOrSignature: "depositForEndpointHash"
  ): TypedContractMethod<[endpointHash: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "endpointBalance"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "endpointGasShareBps"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "endpointGasShareIsSet"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "endpointOwner"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundAndSetGasShare"
  ): TypedContractMethod<[url: string, bps: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalSponsored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postOp"
  ): TypedContractMethod<
    [
      mode: BigNumberish,
      context: BytesLike,
      actualGasCost: BigNumberish,
      actualUserOpFeePerGas: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasShare"
  ): TypedContractMethod<
    [url: string, bps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGasShareByHash"
  ): TypedContractMethod<
    [endpointHash: BytesLike, bps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCalls"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSponsored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockStake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatePaymasterUserOp"
  ): TypedContractMethod<
    [
      userOp: PackedUserOperationStruct,
      userOpHash: BytesLike,
      maxCost: BigNumberish
    ],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawEndpointBalance"
  ): TypedContractMethod<[url: string, to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[withdrawAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTo"
  ): TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EndpointFunded"
  ): TypedContractEvent<
    EndpointFundedEvent.InputTuple,
    EndpointFundedEvent.OutputTuple,
    EndpointFundedEvent.OutputObject
  >;
  getEvent(
    key: "EndpointGasShareSet"
  ): TypedContractEvent<
    EndpointGasShareSetEvent.InputTuple,
    EndpointGasShareSetEvent.OutputTuple,
    EndpointGasShareSetEvent.OutputObject
  >;
  getEvent(
    key: "EndpointWithdraw"
  ): TypedContractEvent<
    EndpointWithdrawEvent.InputTuple,
    EndpointWithdrawEvent.OutputTuple,
    EndpointWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "GasSponsored"
  ): TypedContractEvent<
    GasSponsoredEvent.InputTuple,
    GasSponsoredEvent.OutputTuple,
    GasSponsoredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "EndpointFunded(bytes32,address,uint256)": TypedContractEvent<
      EndpointFundedEvent.InputTuple,
      EndpointFundedEvent.OutputTuple,
      EndpointFundedEvent.OutputObject
    >;
    EndpointFunded: TypedContractEvent<
      EndpointFundedEvent.InputTuple,
      EndpointFundedEvent.OutputTuple,
      EndpointFundedEvent.OutputObject
    >;

    "EndpointGasShareSet(bytes32,uint16)": TypedContractEvent<
      EndpointGasShareSetEvent.InputTuple,
      EndpointGasShareSetEvent.OutputTuple,
      EndpointGasShareSetEvent.OutputObject
    >;
    EndpointGasShareSet: TypedContractEvent<
      EndpointGasShareSetEvent.InputTuple,
      EndpointGasShareSetEvent.OutputTuple,
      EndpointGasShareSetEvent.OutputObject
    >;

    "EndpointWithdraw(bytes32,address,uint256)": TypedContractEvent<
      EndpointWithdrawEvent.InputTuple,
      EndpointWithdrawEvent.OutputTuple,
      EndpointWithdrawEvent.OutputObject
    >;
    EndpointWithdraw: TypedContractEvent<
      EndpointWithdrawEvent.InputTuple,
      EndpointWithdrawEvent.OutputTuple,
      EndpointWithdrawEvent.OutputObject
    >;

    "GasSponsored(address,bytes32,uint256,uint16)": TypedContractEvent<
      GasSponsoredEvent.InputTuple,
      GasSponsoredEvent.OutputTuple,
      GasSponsoredEvent.OutputObject
    >;
    GasSponsored: TypedContractEvent<
      GasSponsoredEvent.InputTuple,
      GasSponsoredEvent.OutputTuple,
      GasSponsoredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
