/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PublisherRegistry {
  export type EndpointStruct = {
    id: BigNumberish;
    publisher: AddressLike;
    url: string;
    pricePerCall: BigNumberish;
    paymasterAddress: AddressLike;
    isActive: boolean;
    totalCalls: BigNumberish;
    totalRevenue: BigNumberish;
    createdAt: BigNumberish;
    requireWorldId: boolean;
  };

  export type EndpointStructOutput = [
    id: bigint,
    publisher: string,
    url: string,
    pricePerCall: bigint,
    paymasterAddress: string,
    isActive: boolean,
    totalCalls: bigint,
    totalRevenue: bigint,
    createdAt: bigint,
    requireWorldId: boolean
  ] & {
    id: bigint;
    publisher: string;
    url: string;
    pricePerCall: bigint;
    paymasterAddress: string;
    isActive: boolean;
    totalCalls: bigint;
    totalRevenue: bigint;
    createdAt: bigint;
    requireWorldId: boolean;
  };
}

export interface PublisherRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateEndpoint"
      | "deactivateEndpoint"
      | "endpoints"
      | "getEndpoint"
      | "getPublisherEndpoints"
      | "getTotalEndpoints"
      | "isSponsored"
      | "nextEndpointId"
      | "owner"
      | "publisherEndpoints"
      | "recordCall"
      | "registerEndpoint"
      | "renounceOwnership"
      | "setRequireWorldId"
      | "setTrustedCaller"
      | "transferOwnership"
      | "trustedCaller"
      | "updatePaymaster"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallRecorded"
      | "EndpointActivated"
      | "EndpointDeactivated"
      | "EndpointRegistered"
      | "OwnershipTransferred"
      | "PaymasterUpdated"
      | "WorldIdRequirementSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateEndpoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateEndpoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endpoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndpoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublisherEndpoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalEndpoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSponsored",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEndpointId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publisherEndpoints",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEndpoint",
    values: [string, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRequireWorldId",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePaymaster",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endpoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublisherEndpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalEndpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEndpointId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publisherEndpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequireWorldId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePaymaster",
    data: BytesLike
  ): Result;
}

export namespace CallRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    caller: AddressLike,
    revenue: BigNumberish
  ];
  export type OutputTuple = [id: bigint, caller: string, revenue: bigint];
  export interface OutputObject {
    id: bigint;
    caller: string;
    revenue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndpointActivatedEvent {
  export type InputTuple = [id: BigNumberish, publisher: AddressLike];
  export type OutputTuple = [id: bigint, publisher: string];
  export interface OutputObject {
    id: bigint;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndpointDeactivatedEvent {
  export type InputTuple = [id: BigNumberish, publisher: AddressLike];
  export type OutputTuple = [id: bigint, publisher: string];
  export interface OutputObject {
    id: bigint;
    publisher: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EndpointRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    publisher: AddressLike,
    url: string,
    pricePerCall: BigNumberish,
    paymasterAddress: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    publisher: string,
    url: string,
    pricePerCall: bigint,
    paymasterAddress: string
  ];
  export interface OutputObject {
    id: bigint;
    publisher: string;
    url: string;
    pricePerCall: bigint;
    paymasterAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymasterUpdatedEvent {
  export type InputTuple = [id: BigNumberish, paymasterAddress: AddressLike];
  export type OutputTuple = [id: bigint, paymasterAddress: string];
  export interface OutputObject {
    id: bigint;
    paymasterAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorldIdRequirementSetEvent {
  export type InputTuple = [id: BigNumberish, required: boolean];
  export type OutputTuple = [id: bigint, required: boolean];
  export interface OutputObject {
    id: bigint;
    required: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PublisherRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PublisherRegistry;
  waitForDeployment(): Promise<this>;

  interface: PublisherRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateEndpoint: TypedContractMethod<
    [endpointId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivateEndpoint: TypedContractMethod<
    [endpointId: BigNumberish],
    [void],
    "nonpayable"
  >;

  endpoints: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        publisher: string;
        url: string;
        pricePerCall: bigint;
        paymasterAddress: string;
        isActive: boolean;
        totalCalls: bigint;
        totalRevenue: bigint;
        createdAt: bigint;
        requireWorldId: boolean;
      }
    ],
    "view"
  >;

  getEndpoint: TypedContractMethod<
    [endpointId: BigNumberish],
    [PublisherRegistry.EndpointStructOutput],
    "view"
  >;

  getPublisherEndpoints: TypedContractMethod<
    [publisher: AddressLike],
    [bigint[]],
    "view"
  >;

  getTotalEndpoints: TypedContractMethod<[], [bigint], "view">;

  isSponsored: TypedContractMethod<
    [endpointId: BigNumberish],
    [boolean],
    "view"
  >;

  nextEndpointId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  publisherEndpoints: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  recordCall: TypedContractMethod<
    [endpointId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerEndpoint: TypedContractMethod<
    [url: string, pricePerCall: BigNumberish, paymasterAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRequireWorldId: TypedContractMethod<
    [endpointId: BigNumberish, required: boolean],
    [void],
    "nonpayable"
  >;

  setTrustedCaller: TypedContractMethod<
    [_caller: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedCaller: TypedContractMethod<[], [string], "view">;

  updatePaymaster: TypedContractMethod<
    [endpointId: BigNumberish, paymasterAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateEndpoint"
  ): TypedContractMethod<[endpointId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateEndpoint"
  ): TypedContractMethod<[endpointId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endpoints"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        publisher: string;
        url: string;
        pricePerCall: bigint;
        paymasterAddress: string;
        isActive: boolean;
        totalCalls: bigint;
        totalRevenue: bigint;
        createdAt: bigint;
        requireWorldId: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEndpoint"
  ): TypedContractMethod<
    [endpointId: BigNumberish],
    [PublisherRegistry.EndpointStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublisherEndpoints"
  ): TypedContractMethod<[publisher: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTotalEndpoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isSponsored"
  ): TypedContractMethod<[endpointId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextEndpointId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publisherEndpoints"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCall"
  ): TypedContractMethod<[endpointId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerEndpoint"
  ): TypedContractMethod<
    [url: string, pricePerCall: BigNumberish, paymasterAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequireWorldId"
  ): TypedContractMethod<
    [endpointId: BigNumberish, required: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedCaller"
  ): TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updatePaymaster"
  ): TypedContractMethod<
    [endpointId: BigNumberish, paymasterAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CallRecorded"
  ): TypedContractEvent<
    CallRecordedEvent.InputTuple,
    CallRecordedEvent.OutputTuple,
    CallRecordedEvent.OutputObject
  >;
  getEvent(
    key: "EndpointActivated"
  ): TypedContractEvent<
    EndpointActivatedEvent.InputTuple,
    EndpointActivatedEvent.OutputTuple,
    EndpointActivatedEvent.OutputObject
  >;
  getEvent(
    key: "EndpointDeactivated"
  ): TypedContractEvent<
    EndpointDeactivatedEvent.InputTuple,
    EndpointDeactivatedEvent.OutputTuple,
    EndpointDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "EndpointRegistered"
  ): TypedContractEvent<
    EndpointRegisteredEvent.InputTuple,
    EndpointRegisteredEvent.OutputTuple,
    EndpointRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymasterUpdated"
  ): TypedContractEvent<
    PaymasterUpdatedEvent.InputTuple,
    PaymasterUpdatedEvent.OutputTuple,
    PaymasterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WorldIdRequirementSet"
  ): TypedContractEvent<
    WorldIdRequirementSetEvent.InputTuple,
    WorldIdRequirementSetEvent.OutputTuple,
    WorldIdRequirementSetEvent.OutputObject
  >;

  filters: {
    "CallRecorded(uint256,address,uint256)": TypedContractEvent<
      CallRecordedEvent.InputTuple,
      CallRecordedEvent.OutputTuple,
      CallRecordedEvent.OutputObject
    >;
    CallRecorded: TypedContractEvent<
      CallRecordedEvent.InputTuple,
      CallRecordedEvent.OutputTuple,
      CallRecordedEvent.OutputObject
    >;

    "EndpointActivated(uint256,address)": TypedContractEvent<
      EndpointActivatedEvent.InputTuple,
      EndpointActivatedEvent.OutputTuple,
      EndpointActivatedEvent.OutputObject
    >;
    EndpointActivated: TypedContractEvent<
      EndpointActivatedEvent.InputTuple,
      EndpointActivatedEvent.OutputTuple,
      EndpointActivatedEvent.OutputObject
    >;

    "EndpointDeactivated(uint256,address)": TypedContractEvent<
      EndpointDeactivatedEvent.InputTuple,
      EndpointDeactivatedEvent.OutputTuple,
      EndpointDeactivatedEvent.OutputObject
    >;
    EndpointDeactivated: TypedContractEvent<
      EndpointDeactivatedEvent.InputTuple,
      EndpointDeactivatedEvent.OutputTuple,
      EndpointDeactivatedEvent.OutputObject
    >;

    "EndpointRegistered(uint256,address,string,uint256,address)": TypedContractEvent<
      EndpointRegisteredEvent.InputTuple,
      EndpointRegisteredEvent.OutputTuple,
      EndpointRegisteredEvent.OutputObject
    >;
    EndpointRegistered: TypedContractEvent<
      EndpointRegisteredEvent.InputTuple,
      EndpointRegisteredEvent.OutputTuple,
      EndpointRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymasterUpdated(uint256,address)": TypedContractEvent<
      PaymasterUpdatedEvent.InputTuple,
      PaymasterUpdatedEvent.OutputTuple,
      PaymasterUpdatedEvent.OutputObject
    >;
    PaymasterUpdated: TypedContractEvent<
      PaymasterUpdatedEvent.InputTuple,
      PaymasterUpdatedEvent.OutputTuple,
      PaymasterUpdatedEvent.OutputObject
    >;

    "WorldIdRequirementSet(uint256,bool)": TypedContractEvent<
      WorldIdRequirementSetEvent.InputTuple,
      WorldIdRequirementSetEvent.OutputTuple,
      WorldIdRequirementSetEvent.OutputObject
    >;
    WorldIdRequirementSet: TypedContractEvent<
      WorldIdRequirementSetEvent.InputTuple,
      WorldIdRequirementSetEvent.OutputTuple,
      WorldIdRequirementSetEvent.OutputObject
    >;
  };
}
