/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReviewRegistry {
  export type ReviewStruct = {
    reviewer: AddressLike;
    endpointId: BigNumberish;
    score: BigNumberish;
    commentHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type ReviewStructOutput = [
    reviewer: string,
    endpointId: bigint,
    score: bigint,
    commentHash: string,
    timestamp: bigint
  ] & {
    reviewer: string;
    endpointId: bigint;
    score: bigint;
    commentHash: string;
    timestamp: bigint;
  };
}

export interface ReviewRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "endpointAvgRating"
      | "endpointReviewCount"
      | "endpointReviews"
      | "endpointTotalScore"
      | "getEndpointReviews"
      | "getReviewCount"
      | "hasReviewed"
      | "owner"
      | "publisherAvgRating"
      | "publisherReviewCount"
      | "publisherTotalScore"
      | "rate"
      | "rateVerified"
      | "renounceOwnership"
      | "setTrustedRelayer"
      | "transferOwnership"
      | "trustedRelayer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReviewSubmitted"
      | "ReviewUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "endpointAvgRating",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointReviewCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointReviews",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointTotalScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndpointReviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publisherAvgRating",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publisherReviewCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publisherTotalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rate",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rateVerified",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedRelayer",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "endpointAvgRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointReviewCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEndpointReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReviewCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publisherAvgRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publisherReviewCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publisherTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedRelayer",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    endpointId: BigNumberish,
    reviewer: AddressLike,
    publisher: AddressLike,
    score: BigNumberish,
    commentHash: BytesLike
  ];
  export type OutputTuple = [
    endpointId: bigint,
    reviewer: string,
    publisher: string,
    score: bigint,
    commentHash: string
  ];
  export interface OutputObject {
    endpointId: bigint;
    reviewer: string;
    publisher: string;
    score: bigint;
    commentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewUpdatedEvent {
  export type InputTuple = [
    endpointId: BigNumberish,
    reviewer: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    endpointId: bigint,
    reviewer: string,
    oldScore: bigint,
    newScore: bigint
  ];
  export interface OutputObject {
    endpointId: bigint;
    reviewer: string;
    oldScore: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReviewRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReviewRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReviewRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  endpointAvgRating: TypedContractMethod<
    [endpointId: BigNumberish],
    [bigint],
    "view"
  >;

  endpointReviewCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  endpointReviews: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, string, bigint] & {
        reviewer: string;
        endpointId: bigint;
        score: bigint;
        commentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  endpointTotalScore: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getEndpointReviews: TypedContractMethod<
    [endpointId: BigNumberish],
    [ReviewRegistry.ReviewStructOutput[]],
    "view"
  >;

  getReviewCount: TypedContractMethod<
    [endpointId: BigNumberish],
    [bigint],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publisherAvgRating: TypedContractMethod<
    [publisher: AddressLike],
    [bigint],
    "view"
  >;

  publisherReviewCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  publisherTotalScore: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  rate: TypedContractMethod<
    [
      endpointId: BigNumberish,
      publisher: AddressLike,
      score: BigNumberish,
      commentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rateVerified: TypedContractMethod<
    [
      reviewer: AddressLike,
      endpointId: BigNumberish,
      publisher: AddressLike,
      score: BigNumberish,
      commentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setTrustedRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedRelayer: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "endpointAvgRating"
  ): TypedContractMethod<[endpointId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "endpointReviewCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "endpointReviews"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, string, bigint] & {
        reviewer: string;
        endpointId: bigint;
        score: bigint;
        commentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "endpointTotalScore"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEndpointReviews"
  ): TypedContractMethod<
    [endpointId: BigNumberish],
    [ReviewRegistry.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReviewCount"
  ): TypedContractMethod<[endpointId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publisherAvgRating"
  ): TypedContractMethod<[publisher: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publisherReviewCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publisherTotalScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rate"
  ): TypedContractMethod<
    [
      endpointId: BigNumberish,
      publisher: AddressLike,
      score: BigNumberish,
      commentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rateVerified"
  ): TypedContractMethod<
    [
      reviewer: AddressLike,
      endpointId: BigNumberish,
      publisher: AddressLike,
      score: BigNumberish,
      commentHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedRelayer"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewUpdated"
  ): TypedContractEvent<
    ReviewUpdatedEvent.InputTuple,
    ReviewUpdatedEvent.OutputTuple,
    ReviewUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,address,address,uint8,bytes32)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;

    "ReviewUpdated(uint256,address,uint8,uint8)": TypedContractEvent<
      ReviewUpdatedEvent.InputTuple,
      ReviewUpdatedEvent.OutputTuple,
      ReviewUpdatedEvent.OutputObject
    >;
    ReviewUpdated: TypedContractEvent<
      ReviewUpdatedEvent.InputTuple,
      ReviewUpdatedEvent.OutputTuple,
      ReviewUpdatedEvent.OutputObject
    >;
  };
}
