/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPaymentSplitter,
  IPaymentSplitterInterface,
} from "../../../contracts/PublisherRegistry.sol/IPaymentSplitter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "endpointId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "publisher",
        type: "address",
      },
    ],
    name: "registerPublisher",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPaymentSplitter__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymentSplitterInterface {
    return new Interface(_abi) as IPaymentSplitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPaymentSplitter {
    return new Contract(address, _abi, runner) as unknown as IPaymentSplitter;
  }
}
