/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPaymentSplitter } from "./IPaymentSplitter";
export type { PublisherRegistry } from "./PublisherRegistry";
